### ISSUE TITLE
createOnly problem

### ISSUE THREAD

**Issue by warioss** [dashjoin/json-schema-form#101]
Hello everybody,
I am writing to you since I noticed that the **createOnly** function reported in the _demo_ at this _link_: 
https://dashjoin.github.io/#/
does not work if tested in _stackblitz_: 
https://stackblitz.com/edit/dashjoin-t1hv3d
Could you tell me if is it a bug or am I doing something wrong? 
Thanks a lot in advance.

**Comment by aeberhart** [comment]
Your stackblitz works if you assign one of the fields to value:

  value: any = {
    exists: "test"
  };

Please note that createOnly is not defined in the JSON schema standard. We included it for use cases where you have a relational DB. The primary key of a record is marked with createOnly. This allows you to use the same form when you create a new record (you actually must specify the pk) and when you update a record (where usually you do not want to allow the user the change the key).

**Comment by warioss** [comment]
Hi aeberhart, thank you very much for the explanations and kindness, now everything is clear and it works 👍
