### ISSUE TITLE
how can i use the forked dashjoin / json-schema-form in my project?

### ISSUE THREAD

**Issue by imranaalam** [dashjoin/json-schema-form#112]
i have forked the dashjoin / json-schema-form project. but, I don't know how to use it in my project. i have followed https://stackoverflow.com/questions/40528053/npm-install-and-build-of-forked-github-repo
but could not be successful.

**Comment by aeberhart** [comment]
The normal way is via npm. This means we merge the change and publish the next version with your change, let's say 0.8.4.
You can also build locally. In essence, npm also just "copies" the dist folder into the new project.

**Comment by imranaalam** [comment]
yes, it's surely the ideal way.

 some workaround I found at
https://stackoverflow.com/questions/43770328/two-versions-of-same-npm-package-in-node-application

based on which the following setup was successful:

package.json
 "@dashjoin/json-schema-form": "git+https://github.com/imranaalam/json-schema-form.git",

then 
npm i
(build not required as its already have dist folder included in the repo (in .gitignore "/dist "  was commented out. meaning git will not ignore it.

where 
https://github.com/imranaalam/json-schema-form.git
is the forked repo

in page component imported from
import { Schema } from '@dashjoin/json-schema-form/dist/dashjoin/json-schema-form';

in moduleimported from 
import { JsonSchemaFormModule } from '@dashjoin/json-schema-form/dist/dashjoin/json-schema-form';

**Comment by imranaalam** [comment]
"You can also build locally. In essence, npm also just "copies" the dist folder into the new project."

is the best method
make a project from this repo (or stackblitz it)
npm i 

ng build @dashjoin/json-schema-form --watch
this command keeps watching for changes in the actual module located in "projects"
ng serve
this runs the demo app

make changes

copy the dist folder  and replaceit in your project json-schema-form library dist folder

**Comment by aeberhart** [comment]
Seems like this is resolved. Can you close the issue?
