### ISSUE TITLE
validation issue for numbers

### ISSUE THREAD

**Issue by fariz1992** [dashjoin/json-schema-form#144]
the following code block doesn't work.
```
if (this.schema.minimum) {  
        if (!(Number(this.value) >= this.schema.minimum)) {
          return this.e('Must greater than or equal ' + this.schema.minimum);
        }
}
```

**Comment by aeberhart** [comment]
If you visit https://dashjoin.github.io/#/example/maximum and change "maximum" to "minimum" it works fine.
Can you list your steps to reproduce?

**Comment by fariz1992** [comment]
still doesn't work for 0
![image](https://user-images.githubusercontent.com/5210578/160900621-c39bda69-63f7-4411-8ae8-b2966fe85199.png)

**Comment by aeberhart** [comment]
ok - you're right
if (this.schema.minimum)
evaluates to false if minimum is zero!
