### ISSUE TITLE
array validation issue

### ISSUE THREAD

**Issue by fariz1992** [dashjoin/json-schema-form#146]
if an array is required and its value is [ ], it doesn't validate the array.
ex: 
![image](https://user-images.githubusercontent.com/5210578/161352861-7443d853-17ae-468d-aceb-71f7e10fc03b.png)

**Comment by aeberhart** [comment]
This is actually correct according to the spec:
https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.5.3

and this validator:
https://www.jsonschemavalidator.net/s/rA8lIHcu
