### ISSUE TITLE
Update to Angular 15

### ISSUE THREAD

**Issue by ldamet** [dashjoin/json-schema-form#168]
Hi,

I would like to integrate json-schema-form in an Angular15 project. Right now it will not build because of incompatibilities with angular-material changes done in angular 15.

This seems fixed by #161 merge request

Thank you.

**Comment by aeberhart** [comment]
we're working on it right now - unfortunately the PR breaks the layout, that's why we didn't merge it yet

**Comment by ldamet** [comment]
Great, thank's a lot!

**Comment by aeberhart** [comment]
we just published version 1.0.0 which uses angular 15
please let us know if you find any issues!
