### ISSUE TITLE
Remove BrowserModule dep

### ISSUE THREAD

**Issue by peterdolenc** [dashjoin/json-schema-form#174]
Since a recent change after angular 15 update you included BrowserModule within the imports of the JsonSchemaFormModule.
BrowserModule should only be imported once per app. 
If one uses the JsonSchemaFormComponent in a lazy loaded module (like us), then that module will fail to be loaded with the error:

`Error: Providers from the `BrowserModule` have already been loaded. If you need access to common directives such as NgIf and NgFor, import the `CommonModule` instead.`

**Comment by LuigiElleBalotta** [comment]
Bump!

**Comment by aeberhart** [comment]
removed the lib and published version 1.0.1
