### ISSUE TITLE
support Angular Material Chips

### ISSUE THREAD

**Issue by aeberhart** [dashjoin/json-schema-form#40]
https://material.angular.io/components/chips/examples

**Comment by titusfx** [comment]
I think you are the only person maintaining this project. Looking this issue that you open I will suggest doing something general to components. In that way you don't need to keep up with new widgets.
For instance: [here](https://github.com/dashjoin/json-schema-form#custom-widgets) you explain how to do a custom widget and your [interface widget is too simple](https://github.com/dashjoin/json-schema-form/blob/master/projects/dashjoin/json-schema-form/src/lib/widget.component.ts) may be need some change to support multiples inputs values and outputs (or values changes/events). I think a good one could be a native, that has events, and can be extended easily maybe a webcomponent directly.

Once that is defined, you could add angular components without caring where it comes, in this case could be the same path that we use on typescript files with **import** using that path as identifier.

**Comment by aeberhart** [comment]
Thanks for your suggestion. You are right that the custom widget mechanism does not support all functionality yet. Specifically, when the JSON value is changed outside, the component does not pick up the change (can be tested by using the custom example on the playground and changing the value in the textfield). Also, the validation does not work if the custom component "owns" more than a single value. I opened an issue for this (https://github.com/dashjoin/json-schema-form/issues/46).

In the WidgetComponent interface, actually, valueChange is an output and all others are inputs. I didn't add the Input / Output annotations because I have to use the dynamic component loader (https://angular.io/guide/dynamic-component-loader). This is where the inputs are passed and the output event is forwarded:

https://github.com/dashjoin/json-schema-form/blob/0c8b26f770258fed13307afb2914e3567af30c99/projects/dashjoin/json-schema-form/src/lib/json-schema-form.component.ts#L831

I'll also try to add a better / more meaningful example and document the component interaction better.

Does this make sense or am I missing something?

**Comment by aeberhart** [comment]
first version. some restrictions do apply (no autocomplete, no format validation, no styling of the input component)
