### ISSUE TITLE
Static choice not selectable with arrow keys (only with mouse)

### ISSUE THREAD

**Issue by fischermc** [dashjoin/json-schema-form#58]
I am not sure if this is by design. For me the selection my arrow keys up / down would make sense:

![image](https://user-images.githubusercontent.com/69622899/91532033-ff94a600-e90d-11ea-89c4-09c5d7bba4e8.png)

**Comment by aeberhart** [comment]
This is by design, since the keyboard focus is in the textfield (I agree that this really is limited to left & right - up and down could be used this way).
Also see https://material.angular.io/components/autocomplete/examples
