### ISSUE TITLE
Is it possible to change the date format?

### ISSUE THREAD

**Issue by Salmu96** [dashjoin/json-schema-form#71]
Hi, congratulations on a fantastic job.
I would like to know if it is possible to change the date format of the output JSON.

I now explain better to you what I mean.
Let's consider the following example: https://stackblitz.com/edit/dashjoin as you can see in the INPUT FORM the date format is mm / dd / yyyy (for example 10/9/2020), BUT in the output json data printed below the format is: "bday" : "2020-10-08T22: 00: 00.000Z".
I'd like to mantain mm / dd / yyyy even in the output json file.

If it is not possible, can I in some way create a custom widget in order to reach my goal?

Thank you in advance ^^

**Comment by aeberhart** [comment]
We choose the ISO date encoding as a default. We could reuse the "format" field, which is used to validate regular expressions:

```
{
  "type": "string",
  "widget": "date",
  "format": "yyyy-MM-dd"  
}
```

The format strings could be like these: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
Do you know of a JS / TS equivalent?

**Comment by Salmu96** [comment]
Hi @aeberhart , thank you very much for your reply.

I tried to insert "format": "yyyy-MM-dd" as you can see here: https://stackblitz.com/edit/dashjoin-ra4ve5 and in this way, the string is validated but the output printed below in the json-data is again "bday": "2020-10-19T22: 00: 00.000Z" while I would like it to be "bday": "10-20-2020", how could I get all this? I hope I explained myself correctly, I wish you a good day ^^

**Comment by aeberhart** [comment]
It's not implemented yet :) Actually, it's probably better to introduce a new field "dateFormat". This way, one could additionally use a regex to specify a pattern the date has to comply with.
Should have it ready this week.

**Comment by Salmu96** [comment]
Thank you very much @aeberhart , you have been very kind and extremely available, I wish you a nice day ^^

**Comment by aeberhart** [comment]
published the new version to stackblitz, npm & github
let me know if this works out for you

**Comment by Salmu96** [comment]
> published the new version to stackblitz, npm & github
> let me know if this works out for you

Thank you very much @aeberhart, it works perfectly. Magnificent work ^^
I can consider close and resolved this issue.
