### ISSUE TITLE
How do you show the tooltip on the form input fields?

### ISSUE THREAD

**Issue by Salmu96** [dashjoin/json-schema-form#72]
Hello everyone!

I read in the demo: https://dashjoin.github.io/#/ that by inserting the "description proprerty" in a JsonSchema, a tooltip should appear that shows you the value of the "description property".

But in the demo itself this doesn't work: if you click on https://dashjoin.github.io/#/ and click on "description button" above then you left the cursor on the input field, it won't show the description. And even in my personal angular project the "description property" isn't shown as tooltip. 
You can see the example I was talking about in this screen:
![Doesn't Work](https://user-images.githubusercontent.com/72612398/95787318-90b2b700-0cd9-11eb-8ea5-a20f4bee1071.jpeg) 

While, if I use the stackblitz, then it works: https://stackblitz.com/edit/dashjoin-ifeplp
You can see the example I was talking about in this screen:
![It works](https://user-images.githubusercontent.com/72612398/95787326-93151100-0cd9-11eb-889c-e8f791198129.jpeg)

I dunno why in demo and in my own angular application this doesn't work, while in stackblitz it works perfectly. 
Can you help me to understand the reason? 

Thank you in Adavance

**Comment by aeberhart** [comment]
Good catch! We had this in an earlier version but had to remove the feature because the tooltip causes problems when the page is displayed on mobile devices:

https://github.com/dashjoin/json-schema-form/blob/7892bd20dab6171d18c3ca2fc2f77bd61764ecbf/projects/dashjoin/json-schema-form/src/lib/json-schema-form.component.html#L12

The plan is to reenable this feature once the angular issue is fixed.
We should probably note this in the documentation.

**Comment by Salmu96** [comment]
Thank you very much @aeberhart, very kind and precise as always ^^

**Comment by aeberhart** [comment]
published the new version to stackblitz, npm & github
let me know if this works out for you

**Comment by Salmu96** [comment]
> published the new version to stackblitz, npm & github
> let me know if this works out for you

Hi @aeberhart, I update to new versione with npm but if I add 

`"<lib-json-schema-form [matTooltip]="schema.description" [(value)]="value" [schema]="schema" [label]="schema.title" (errorChange)="error=$event"></lib-json-schema-form>"` 

the compiler says:

> ERROR in Can't bind to 'matTooltip' since it isn't a known property of 'lib-json-schema-form'.

> 1. If 'lib-json-schema-form' is an Angular component and it has 'matTooltip' input, then verify that it is part of this module.

> 2. If 'lib-json-schema-form' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("  <p class="alert alert-danger">{{error}}<p>

 

>        </ng-template>

>  <lib-json-schema-form [ERROR ->][matTooltip]="schema.description" [(value)]="value" [schema]="schema" [label]="schema.title" (errorCh")

**Comment by aeberhart** [comment]
Yes, this does not work. You'd have to put the tooltip in a surrounding div.

**Comment by aeberhart** [comment]
Re-enabled the tooltip in the component.
Still disabled on mobile though.

Please let me know if this works for you

**Comment by Salmu96** [comment]
> Re-enabled the tooltip in the component.
> Still disabled on mobile though.
> 
> Please let me know if this works for you

Hi @aeberhart,
I congratulate with you for your skills and availability, now with version 0.4.4 of this lib even the tooltips work perfectly if the "property description" is added to the jsonschema. 
For me such issue can be closed ^ _ ^
