### ISSUE TITLE
readOnly doesn't work with widget select 

### ISSUE THREAD

**Issue by Salmu96** [dashjoin/json-schema-form#92]
Hello everyone, as the title suggests, the readOnly property seems to be not working with the widget select , here is an example: https://stackblitz.com/edit/dashjoin-h7nz7v

How could this be solved? Thanks to all in advance :D

**Comment by aeberhart** [comment]
good catch! will be fixed with version 0.6.0 later tody

**Comment by aeberhart** [comment]
let me know if it works for you

**Comment by Salmu96** [comment]
Now it works perfectly, thank you 👍
