### ISSUE TITLE
Problems with autocomplete on type array with item of type string 

### ISSUE THREAD

**Issue by Salmu96** [dashjoin/json-schema-form#96]
Hello everyone! I am writing to you because I have noticed that when I create an array type schema with an item of type string and add the autocomplete on it, every time I write a character in the field, the focus on the field is lost and I have to reclick on the field to insert the next character.
Here is an example: https://stackblitz.com/edit/dashjoin-darngi?file=src%2Fapp%2Fapp.component.ts
Is it possible to fix this bug to allow autocomplete on this type of schema present in the example above? Thanks a lot in advance.

**Comment by aeberhart** [comment]
Thanks for reporting this. We'll have a look!
